[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
uci = {path = "../uci/"}
static_init = "1.0.3"
bitflags = "2.5.0"
rand = "0.8.5"
rayon = "1.10.0"

[build-dependencies]
reqwest = {version = "0.12.4", features = ["blocking"]}
