name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install nightly
      run: rustup toolchain install nightly
    - name: default nightly 
      run: rustup default nightly
    - name: Build
      run: cargo build --release --verbose
    - name: Test
      run: cargo test --release --verbose

